// src/constants/womenFashionBrands.js
export const globalBrands = [
  "1More",
  "2Eros",
  "2XU",
  "361°",
  "3INA",
  "3M",
  "4F",
  "7 For All Mankind",
  "8BitDo",
  "A Bathing Ape",
  "A.P.C.",
  "Aaiko",
  "Aaptiv",
  "Abercrombie & Fitch",
  "Absolut",
  "Acana",
  "Acer",
  "Acne Studios",
  "Acqua di Parma",
  "Acronym",
  "Adanola",
  "Adidas",
  "Adobe",
  "AEG",
  "Aerin",
  "Aesop",
  "Afends",
  "Agent Provocateur",
  "Agolde",
  "Aigle",
  "Aime Leon Dore",
  "Airbnb",
  "Akai",
  "Akasa",
  "Akris",
  "Aldo",
  "Alessi",
  "Alexander McQueen",
  "Alexander Wang",
  "Alex and Ani",
  "All Saints",
  "Allbirds",
  "Aloysius",
  "Alpha Industries",
  "Alpina",
  "Altuzarra",
  "Amazon Basics",
  "Amazon Essentials",
  "Ambre Sultan",
  "American Apparel",
  "American Eagle",
  "Amiri",
  "Amouage",
  "Anastasia Beverly Hills",
  "Anchor",
  "Ancient Greek Sandals",
  "Anello",
  "Anine Bing",
  "Anne Klein",
  "Anthropologie",
  "Antler",
  "Anyma",
  "Apc",
  "Apivita",
  "Aquascutum",
  "Arcelik",
  "Arket",
  "Armani",
  "Armani Exchange",
  "Arper",
  "Arte",
  "Arteza",
  "Artisan",
  "Asahi",
  "Asics",
  "ASOS",
  "Astral",
  "Astro",
  "Asus",
  "AT&T",
  "Atelier Cologne",
  "Athleta",
  "Atmos",
  "Atomic",
  "Audio-Technica",
  "Audiolux",
  "Aukey",
  "Aurelia",
  "Authenticity",
  "Aveeno",
  "Avene",
  "Avon",
  "Awake NY",
  "Axe",
  "Ayurveda",
  "Azzaro",
  "B&O",
  "Babyliss",
  "Babyzen",
  "Bacardi",
  "Badgley Mischka",
  "Bagatelle",
  "Baggu",
  "Bague",
  "Balenciaga",
  "Ball",
  "Bally",
  "Balmain",
  "Banana Republic",
  "Bang & Olufsen",
  "Bao Bao Issey Miyake",
  "Bape",
  "Barbour",
  "Bario Neal",
  "Barker",
  "Barnes & Noble",
  "Baseus",
  "Bathing Ape",
  "BaubleBar",
  "Baxter of California",
  "BCBG Max Azria",
  "Beach Riot",
  "Bearpaw",
  "Beats",
  "Beautiful People",
  "Becca",
  "Beckham",
  "Bed Bath & Beyond",
  "Bedgear",
  "Beko",
  "Belkin",
  "Bellroy",
  "Ben Sherman",
  "Benefit",
  "Bentley",
  "Bergdorf Goodman",
  "Bershka",
  "Best Buy",
  "Betts",
  "Beyerdynamic",
  "BH Cosmetics",
  "Billabong",
  "Billion Dollar Brows",
  "Birkenstock",
  "Bisou",
  "Bite Beauty",
  "Blackberry",
  "Blackstone",
  "Blanc",
  "Blazer",
  "Bleu de Chanel",
  "Blind",
  "Bloch",
  "Blondo",
  "Bloomingdale's",
  "Blue Nile",
  "Bluetti",
  "Bobbi Brown",
  "Boden",
  "Body Shop",
  "Bodum",
  "Bombas",
  "Bonobos",
  "Boohoo",
  "Bora Bora",
  "Bose",
  "Boss",
  "Bottega Veneta",
  "Bowers & Wilkins",
  "Box",
  "Braun",
  "Breitling",
  "Brioni",
  "British Airways",
  "Brooks Brothers",
  "Brooks Running",
  "Brother",
  "Brown Thomas",
  "Brunello Cucinelli",
  "BSA",
  "BTS",
  "Bucherer",
  "Budweiser",
  "Buffalo",
  "Bulgari",
  "Bumble and Bumble",
  "Burberry",
  "Burton",
  "Butterfly Twists",
  "Byredo",
  "C&A",
  "Cacique",
  "Cafune",
  "Calvin Klein",
  "Camper",
  "Canada Goose",
  "Canon",
  "Cantu",
  "Capella",
  "Carhartt",
  "Carolina Herrera",
  "Cartier",
  "Casio",
  "Catbird",
  "Caterpillar",
  "Catherine Malandrino",
  "Caudalie",
  "CeraVe",
  "Celine",
  "Centaur",
  "Chaco",
  "Champion",
  "Chanel",
  "Chaos",
  "Charles & Keith",
  "Charles Tyrwhitt",
  "Charlotte Russe",
  "Charlotte Tilbury",
  "Charms",
  "Charter Club",
  "Cheap Monday",
  "Cheerios",
  "Chesterfield",
  "Chevron",
  "Chi",
  "Chicco",
  "Chie Mihara",
  "Chinese Laundry",
  "Chloe",
  "Chopard",
  "Christian Dior",
  "Christian Louboutin",
  "Chrome Hearts",
  "Citizens of Humanity",
  "Citizen",
  "Clarins",
  "Clarks",
  "Clinique",
  "Closet London",
  "Club Monaco",
  "Coach",
  "Coca Cola",
  "Coccinelle",
  "Cole Haan",
  "Colette",
  "Collina Strada",
  "Columbia",
  "Comme des Garcons",
  "Common Projects",
  "Comptoir des Cotonniers",
  "Conair",
  "Converse",
  "Cool",
  "Cooler Master",
  "Corsair",
  "Corteiz",
  "COS",
  "Costco",
  "Cotopaxi",
  "Cotton On",
  "Covergirl",
  "CP Company",
  "Crate & Barrel",
  "Creative",
  "Creed",
  "Crest",
  "Crocs",
  "Crossbody",
  "Cucinelli",
  "Cuisinart",
  "Cult Gaia",
  "Cuyana",
  "CyberPowerPC",
  "Dagne Dover",
  "Dainese",
  "Daisuke Obana",
  "Daniel Wellington",
  "Danner",
  "Dansko",
  "Darling",
  "David Jones",
  "David Yurman",
  "De Beers",
  "DeBrand",
  "Deciem",
  "Defacto",
  "Dell",
  "Delsey",
  "Delta",
  "Denon",
  "Department",
  "Dermalogica",
  "Desigual",
  "DeWalt",
  "DHL",
  "Diane von Furstenberg",
  "Dickies",
  "Diesel",
  "Dior",
  "Disney",
  "DKNY",
  "Dockers",
  "Dolce & Gabbana",
  "Dole",
  "Domyos",
  "Dooney & Bourke",
  "Doritos",
  "Dove",
  "Dr. Martens",
  "Dr. Scholl's",
  "Dragon",
  "Dries Van Noten",
  "Dropbox",
  "Drunk Elephant",
  "Dsquared2",
  "Ducati",
  "Dune London",
  "Dunhill",
  "DuPont",
  "Durex",
  "Dyson",
  "E.L.F.",
  "Eagle",
  "Earnest Sewn",
  "Eastpak",
  "eBags",
  "Ebay",
  "Ecco",
  "Edifier",
  "Egoist",
  "Eight & Bob",
  "Eileen Fisher",
  "Element",
  "Elizabeth Arden",
  "Ellesse",
  "Elsa Peretti",
  "Emilio Pucci",
  "Emporio Armani",
  "Endura",
  "Energizer",
  "Envy",
  "Epic Games",
  "Epson",
  "Equipment",
  "Ermenegildo Zegna",
  "Escada",
  "Essie",
  "Estee Lauder",
  "EssilorLuxottica",
  "Etam",
  "Eternity",
  "Etude House",
  "Eucerin",
  "Everlane",
  "Every Man Jack",
  "Evian",
  "Express",
  "Eyeko",
  "Fabletics",
  "Facebook",
  "Facetasm",
  "Falke",
  "Fame",
  "Farfetch",
  "Fashion Nova",
  "Fay",
  "Fear of God",
  "FedEx",
  "Felix",
  "Fendi",
  "Fenty Beauty",
  "Ferrari",
  "Ferragamo",
  "Fidelity",
  "Figs",
  "Fila",
  "Filippa K",
  "Finch",
  "Fiorelli",
  "Fisher-Price",
  "Fitbit",
  "Fjällräven",
  "Flash",
  "Florsheim",
  "Focal",
  "Fom",
  "Forever 21",
  "Fortnite",
  "Fossil",
  "Fracap",
  "Frame",
  "Frank And Oak",
  "Fred Perry",
  "Free People",
  "French Connection",
  "Fresh",
  "Friday",
  "Frye",
  "Fuji",
  "Furla",
  "G-Star RAW",
  "Gabbana",
  "Gabriela Hearst",
  "Gal Gadot",
  "Galeries Lafayette",
  "Game",
  "Ganni",
  "Gap",
  "Garmin",
  "Gatorade",
  "Geberit",
  "Gentle Monster",
  "George",
  "Giambattista Valli",
  "Gianni Versace",
  "Gift",
  "Gildan",
  "Giorgio Armani",
  "Givenchy",
  "Glamglow",
  "Globe",
  "Glory",
  "Glossier",
  "GMT",
  "GNC",
  "Goat",
  "Godiva",
  "Golden Goose",
  "Goldwell",
  "Google",
  "Gorjana",
  "Grado",
  "Graff",
  "Graham",
  "Grenson",
  "Greyhound",
  "Grlfrnd",
  "Grohe",
  "Grounding",
  "Groupe",
  "Gucci",
  "Guess",
  "Guinness",
  "Gulf",
  "Gymshark",
  "H&M",
  "Haagen-Dazs",
  "Habitat",
  "Haider Ackermann",
  "Hamilton",
  "Hammitt",
  "Hanky Panky",
  "Happy",
  "Hard Rock",
  "Harley Davidson",
  "Harman Kardon",
  "Harry Winston",
  "Havaianas",
  "Hayden",
  "Head",
  "Health",
  "Hedley & Bennett",
  "Heineken",
  "Helly Hansen",
  "Hennessy",
  "Hermes",
  "Heron Preston",
  "Herschel Supply Co.",
  "Hewlett Packard",
  "HiFiMan",
  "Hilary",
  "Hilton",
  "Himmeli",
  "Hipster",
  "History",
  "HM",
  "Hoka One One",
  "Holiday",
  "Hollister",
  "Home Depot",
  "Honda",
  "Hook",
  "Hot Topic",
  "HP",
  "HTC",
  "Hudson Jeans",
  "Hugo Boss",
  "Human Made",
  "Hunter",
  "Hurley",
  "HyperX",
  "IBM",
  "Ice",
  "Iconery",
  "IKEA",
  "Iittala",
  "Illuminati",
  "Iman",
  "Imperial",
  "In The Style",
  "Inditex",
  "Infinity",
  "Ingersoll",
  "Innisfree",
  "Intel",
  "Intex",
  "Invicta",
  "Isaia",
  "Isabel Marant",
  "Issey Miyake",
  "IWC Schaffhausen",
  "J.Crew",
  "J.W.Anderson",
  "Jabra",
  "Jack & Jones",
  "Jack Daniels",
  "Jack Wolfskin",
  "Jacquemus",
  "Jaeger-LeCoultre",
  "James Allen",
  "JanSport",
  "Jaybird",
  "JBL",
  "Jennifer Fisher",
  "Jil Sander",
  "Jimmy Choo",
  "Jnco",
  "John Lewis",
  "John Varvatos",
  "Johnny Was",
  "Johnson & Johnson",
  "Joma",
  "Jordan",
  "Joseph",
  "Joules",
  "Judith Leiber",
  "Jujube",
  "Jura",
  "Just Cavalli",
  "JVC",
  "Kappa",
  "Kate Spade",
  "Keds",
  "Kelty",
  "Kendra Scott",
  "Kenzo",
  "Kering",
  "Keurig",
  "Kiehl's",
  "Kiko Milano",
  "Kindle",
  "King",
  "Kipling",
  "Kit",
  "KitchenAid",
  "Klipsch",
  "Kmart",
  "Knomo",
  "Kohl's",
  "Kooples",
  "Koss",
  "Kylie Cosmetics",
  "L'Oreal",
  "L.L.Bean",
  "La Mer",
  "La Perla",
  "La Prairie",
  "La Roche-Posay",
  "Lacoste",
  "Laduree",
  "Lamborghini",
  "Lancome",
  "Land Rover",
  "Lands' End",
  "Lane Bryant",
  "Lanvin",
  "Lark",
  "Laura Mercier",
  "Lavanila",
  "Le Creuset",
  "Le Labo",
  "Le Specs",
  "League",
  "Lemaire",
  "Lenovo",
  "Les Copains",
  "Levi's",
  "LG",
  "Liberty",
  "Life",
  "Limited",
  "Lindt",
  "Linen",
  "Links",
  "Linus",
  "Liz Claiborne",
  "Loewe",
  "Logitech",
  "Longchamp",
  "Longines",
  "Look",
  "Loro Piana",
  "LOT",
  "Louis Vuitton",
  "Love",
  "Lowe's",
  "LTB",
  "Lucky Brand",
  "Lud",
  "Lululemon",
  "Luna",
  "Luxury",
  "Luxe",
  "Lynx",
  "M.A.C",
  "MAC",
  "Mace",
  "Mack Weldon",
  "Macy's",
  "Madden Girl",
  "Madewell",
  "Madison",
  "Magic",
  "Maison Margiela",
  "Makeupforever",
  "Mamma Mia",
  "Man",
  "Mango",
  "Marc Ecko",
  "Marc Jacobs",
  "Marciano",
  "Marine",
  "Marks & Spencer",
  "Marlboro",
  "Marshall",
  "Marvis",
  "Massimo Dutti",
  "Master & Dynamic",
  "Matalan",
  "Matrix",
  "Maui Jim",
  "Mauri",
  "Max Factor",
  "Max Mara",
  "Maybelline",
  "McDonald's",
  "Me&Ro",
  "Medusa",
  "Melissa",
  "Mercedes",
  "Merrell",
  "Meze Audio",
  "Michael Kors",
  "Microsoft",
  "Mido",
  "Mikimoto",
  "Millennium",
  "Miller",
  "Minnetonka",
  "Missoni",
  "Miu Miu",
  "MM6",
  "Moncler",
  "Monday",
  "Money",
  "Monki",
  "Monoprice",
  "Monster",
  "Montblanc",
  "Moomin",
  "Moose Knuckles",
  "Mori Lee",
  "Moschino",
  "Motorola",
  "Mountain Hardwear",
  "Moynat",
  "MSI",
  "MTV",
  "Muji",
  "Mulberry",
  "Murad",
  "Museum",
  "Mustang",
  "Naf Naf",
  "Napapijri",
  "NASA",
  "Natura",
  "Nautica",
  "NBA",
  "Neiman Marcus",
  "Nespresso",
  "Nestle",
  "Netflix",
  "New Balance",
  "New Look",
  "Next",
  "NFL",
  "Nike",
  "Nikon",
  "Nine West",
  "Nintendo",
  "Nixon",
  "No7",
  "Nobody Denim",
  "Nokia",
  "Nordstrom",
  "North Face",
  "Northface",
  "Nothing",
  "Notre Dame",
  "Novak",
  "NSF",
  "Nvidia",
  "NYX Professional Makeup",
  "O'Neill",
  "Oakley",
  "Ocean",
  "Off-White",
  "Oil of Olay",
  "Old Navy",
  "Old Spice",
  "Olive",
  "Oliver Peoples",
  "Omega",
  "One Plus",
  "Oneida",
  "Onitsuka Tiger",
  "Onyx Boox",
  "Oofos",
  "OppoSuits",
  "Oral-B",
  "Orange",
  "Organic",
  "Origins",
  "Oris",
  "Orlebar Brown",
  "Orvis",
  "Oscar de la Renta",
  "Osprey",
  "Other Stories",
  "Oui",
  "Outdoor Research",
  "Outward Hound",
  "Ovation",
  "Overlap",
  "Oxford",
  "P&G",
  "Pacsun",
  "Palladium",
  "Palm Angels",
  "Pandora",
  "Panerai",
  "Pantene",
  "Paper",
  "Parfois",
  "Parker",
  "Patagonia",
  "Patek Philippe",
  "Patrizia Pepe",
  "Paul & Joe",
  "Paul Smith",
  "Pavement",
  "Peak Design",
  "Pearl",
  "Pendleton",
  "Pepsi",
  "Perfect",
  "Perfekt",
  "Perry Ellis",
  "Peter Millar",
  "Peugeot",
  "PGA",
  "Philips",
  "Philosophy",
  "Phoenix",
  "Phoebe Philo",
  "Phuket",
  "Piaget",
  "Pierre Cardin",
  "Pierre Hardy",
  "Pilot",
  "Pioneer",
  "Plantronics",
  "Playboy",
  "PlayStation",
  "Plaza",
  "Pleats Please",
  "Plinius",
  "Polo Ralph Lauren",
  "Polti",
  "Pop",
  "Porcupine",
  "Porsche Design",
  "Portuguese",
  "Pottery Barn",
  "Prada",
  "Precious",
  "Pretty Little Thing",
  "Prime",
  "Primark",
  "Prince",
  "Private",
  "Proenza Schouler",
  "Prom",
  "Propet",
  "Propper",
  "Puma",
  "Purell",
  "Purple",
  "Qantas",
  "Quay",
  "Queen",
  "Quiksilver",
  "R.M.Williams",
  "Rachel Zoe",
  "Rag & Bone",
  "Ralph Lauren",
  "Rare Beauty",
  "Razer",
  "Ray-Ban",
  "Rebecca Minkoff",
  "Red Bull",
  "Red Wing",
  "Reebok",
  "Reed Krakoff",
  "Reformation",
  "Reiss",
  "Repetto",
  "Reserve",
  "Ressence",
  "Revlon",
  "Rich",
  "Rick Owens",
  "Rider",
  "Rimmel",
  "Rimowa",
  "River Island",
  "Rixo",
  "Roberto Cavalli",
  "Rodd & Gunn",
  "Rolex",
  "Roma",
  "Rothy's",
  "Royal",
  "RRL",
  "Rupert Sanderson",
  "Russian",
  "Sabo",
  "Sacai",
  "Saks Fifth Avenue",
  "Salomon",
  "Salvatore Ferragamo",
  "Sam Edelman",
  "Samsung",
  "Samsonite",
  "Samsoe Samsoe",
  "Sanctuary",
  "Sanderson",
  "Sandqvist",
  "Sanuk",
  "Saucony",
  "Savage X Fenty",
  "Scala",
  "Scandinavian",
  "Scarlett",
  "Schott",
  "Scosha",
  "Scotch & Soda",
  "Scott",
  "Sea",
  "Seiko",
  "Sennheiser",
  "Sephora",
  "Seven",
  "Sharpie",
  "Shell",
  "Shiseido",
  "Shure",
  "Siemens",
  "Silver",
  "Simons",
  "Sinclair",
  "Skechers",
  "Skims",
  "Skullcandy",
  "Slip",
  "Smart",
  "Smeg",
  "Smith",
  "Smythson",
  "Snapchat",
  "Soho",
  "Solange",
  "Sole Society",
  "Solid",
  "Sonia Rykiel",
  "Sony",
  "Soundcore",
  "Spanx",
  "Spark",
  "Speedo",
  "Sperry",
  "Spider",
  "Spotify",
  "Stance",
  "Starbucks",
  "State",
  "SteelSeries",
  "Stella McCartney",
  "Steve Madden",
  "Stone Island",
  "Stuart Weitzman",
  "Studio",
  "Sturdy",
  "Subway",
  "Sugarhill Brighton",
  "Sun",
  "Sunglass Hut",
  "Superdry",
  "Superga",
  "Supreme",
  "Surf",
  "Swatch",
  "Swedish Hasbeens",
  "Swimming",
  "Swiss",
  "T3",
  "Tab",
  "Tadashi Shoji",
  "Tag Heuer",
  "Take",
  "Talbot",
  "TaoTronics",
  "Target",
  "Ted Baker",
  "Temple",
  "Tennis",
  "Tesco",
  "Tesla",
  "Teva",
  "The Kooples",
  "The Limited",
  "The North Face",
  "The Ordinary",
  "The Row",
  "Theia",
  "Theory",
  "Thom Browne",
  "Thomas Sabo",
  "Three",
  "Tidal",
  "Tiffany & Co.",
  "Timberland",
  "Tissot",
  "TJ Maxx",
  "Tod's",
  "Tom Ford",
  "Tom Tailor",
  "Tommy Hilfiger",
  "Tony Burch",
  "Topo Designs",
  "Tory Burch",
  "Total",
  "Totto",
  "Town",
  "Toyota",
  "Transport",
  "Travel",
  "Tricker's",
  "True Religion",
  "Tumi",
  "Turkish",
  "Twitter",
  "Two",
  "Uber",
  "Ugg",
  "Ulta",
  "Under Armour",
  "Undercover",
  "Uniqlo",
  "Unity",
  "Universal",
  "UPS",
  "Urban Decay",
  "Urban Outfitters",
  "US Polo Assn",
  "Utopia",
  "V&A",
  "Vacheron Constantin",
  "Vagabond",
  "Valentino",
  "Valerie",
  "Van Cleef & Arpels",
  "Vans",
  "Vaseline",
  "Vaughan",
  "Vegan",
  "Velvet",
  "Vera Bradley",
  "Versace",
  "Very",
  "Vespa",
  "Vetements",
  "Via Spiga",
  "Vibe",
  "Victoria Beckham",
  "Victoria's Secret",
  "Victorinox",
  "Vilebrequin",
  "Vineyard Vines",
  "Vintage",
  "Virgin",
  "Visa",
  "Vision",
  "Vita",
  "Vivienne Westwood",
  "Vodka",
  "Vogue",
  "Volkswagen",
  "Volvo",
  "Warby Parker",
  "Water",
  "Wave",
  "Weekday",
  "Wellies",
  "West Elm",
  "Westside",
  "Whirlpool",
  "Whistles",
  "White",
  "Whole Foods",
  "Wild",
  "Williams Sonoma",
  "Wilson",
  "Wind",
  "Wine",
  "Wired",
  "Wolford",
  "Wonder",
  "Wood",
  "Woolrich",
  "World",
  "X-Box",
  "Xiaomi",
  "Yamaha",
  "Yeezy",
  "Yes",
  "YSL",
  "Yves Saint Laurent",
  "Zadig & Voltaire",
  "Zales",
  "Zara",
  "Zenith",
  "Zero",
  "Zimmermann",
  "Zion",
  "Zone",
  "Zoom",
  "Zuhair Murad",
  "Zulu",
  "Zwilling",
  "Zyrtec",
  // Turkish Brands
  "Abbate",
  "Abiye",
  "Actuel",
  "Adil Isik",
  "Aker",
  "Akris Point",
  "Altınyıldız",
  "Armine",
  "Atasay",
  "Avva",
  "Ayakkabı Dünyası",
  "Bambi",
  "Batik",
  "Beymen",
  "Biltem",
  "Boyner",
  "Can Bonomo",
  "Ceket",
  "Cemile",
  "Collezione",
  "Damat",
  "DeFacto",
  "Derimod",
  "Desa",
  "Divan",
  "Eda",
  "Efendi",
  "Eker",
  "Enzo",
  "Erdem",
  "Etek",
  "FLO",
  "Fortensia",
  "Goksu",
  "Haluk",
  "Hatemoğlu",
  "Hazal",
  "İnci",
  "İpekyol",
  "Kahve",
  "Kigili",
  "Koton",
  "LC Waikiki",
  "Lufian",
  "Machka",
  "Mango Turkey",
  "Meridyen",
  "Modanisa",
  "Modavin",
  "Network",
  "Nihan",
  "Nurten",
  "Oxxo",
  "Pierre Cardin Turkey",
  "Pitti",
  "Sarar",
  "Setrms",
  "Silk & Cashmere",
  "Süvari",
  "Tanca",
  "Tekbir",
  "Triko",
  "Tuğba",
  "Twist",
  "U.S. Polo Assn Turkey",
  "Vakko",
  "Vera Moda Turkey",
  "Yargıcı",
  "Yeni",
  "Zellbury",
];
