/**
 * Food category and type data for restaurant food listings.
 * Follows the same class-based pattern as AllInOneCategoryData in productData.ts.
 */
export class FoodCategoryData {
  // ------------------------------------------------------
  // 1) Food Categories
  // ------------------------------------------------------
  static readonly kCategories: Array<{ key: string }> = [
    { key: "Kebabs & Grills" },
    { key: "Pide & Lahmacun" },
    { key: "Soups" },
    { key: "Salads" },
    { key: "Appetizers & Meze" },
    { key: "Main Courses" },
    { key: "Rice & Pilaf" },
    { key: "Wraps & Doner" },
    { key: "Seafood" },
    { key: "Breakfast" },
    { key: "Desserts & Pastry" },
    { key: "Beverages" },
    { key: "Fast Food" },
    { key: "Pizza & Pasta" },
    { key: "Vegan & Vegetarian" },
    { key: "World Cuisine" },
  ];

  // ------------------------------------------------------
  // 2) Food Types per Category
  // ------------------------------------------------------
  static readonly kFoodTypes: Record<string, string[]> = {
    "Kebabs & Grills": [
      "Adana Kebab",
      "Urfa Kebab",
      "Iskender Kebab",
      "Shish Kebab",
      "Chicken Kebab",
      "Kofte",
      "Mixed Grill",
      "Lamb Chops",
      "Beyti Kebab",
      "Ali Nazik",
      "Cop Sis",
      "Ciğer Kebab",
      "Tantuni",
      "Other Kebab",
    ],
    "Pide & Lahmacun": [
      "Cheese Pide",
      "Minced Meat Pide",
      "Sucuklu Pide",
      "Kasarli Pide",
      "Kusbasi Pide",
      "Lahmacun",
      "Etli Ekmek",
      "Other Pide",
    ],
    Soups: [
      "Lentil Soup",
      "Tomato Soup",
      "Chicken Soup",
      "Tarhana Soup",
      "Ezogelin Soup",
      "Iskembe Soup",
      "Yayla Soup",
      "Mushroom Soup",
      "Mercimek Soup",
      "Other Soup",
    ],
    Salads: [
      "Shepherd Salad",
      "Caesar Salad",
      "Greek Salad",
      "Seasonal Salad",
      "Rocket Salad",
      "Gavurdagi Salad",
      "Piyaz",
      "Coban Salad",
      "Other Salad",
    ],
    "Appetizers & Meze": [
      "Hummus",
      "Babaganoush",
      "Haydari",
      "Atom",
      "Acili Ezme",
      "Cacik",
      "Sigara Boregi",
      "Icli Kofte",
      "Mercimek Kofte",
      "Yaprak Sarma",
      "Falafel",
      "Mucver",
      "Patlican Soslu",
      "Other Meze",
    ],
    "Main Courses": [
      "Guvec",
      "Moussaka",
      "Imam Bayildi",
      "Karniyarik",
      "Hunkar Begendi",
      "Manti",
      "Su Boregi",
      "Etli Nohut",
      "Tas Kebab",
      "Sac Kavurma",
      "Kuzu Tandir",
      "Yaprak Sarma",
      "Steak",
      "Chicken Schnitzel",
      "Other Main Course",
    ],
    "Rice & Pilaf": [
      "Bulgur Pilaf",
      "Rice Pilaf",
      "Nohutlu Pilav",
      "Ic Pilav",
      "Domatesli Bulgur",
      "Other Pilaf",
    ],
    "Wraps & Doner": [
      "Chicken Doner",
      "Meat Doner",
      "Iskender Doner",
      "Doner Wrap",
      "Tavuk Durum",
      "Et Durum",
      "Tombik Doner",
      "Porsiyon Doner",
      "Other Doner",
    ],
    Seafood: [
      "Grilled Fish",
      "Fried Calamari",
      "Shrimp Casserole",
      "Fish Sandwich",
      "Levrek",
      "Somon",
      "Hamsi",
      "Midye Tava",
      "Midye Dolma",
      "Karides Guvec",
      "Other Seafood",
    ],
    Breakfast: [
      "Turkish Breakfast Plate",
      "Serpme Kahvalti",
      "Menemen",
      "Sahanda Yumurta",
      "Sucuklu Yumurta",
      "Gozleme",
      "Simit",
      "Acma",
      "Pogaca",
      "Other Breakfast",
    ],
    "Desserts & Pastry": [
      "Baklava",
      "Kunefe",
      "Sutlac",
      "Kazandibi",
      "Tavuk Gogsu",
      "Asure",
      "Revani",
      "Lokma",
      "Trilece",
      "Profiterol",
      "Cheesecake",
      "Tiramisu",
      "Brownie",
      "Waffle",
      "Dondurma",
      "Other Dessert",
    ],
    Beverages: [
      "Turkish Tea",
      "Turkish Coffee",
      "Ayran",
      "Fresh Orange Juice",
      "Lemonade",
      "Smoothie",
      "Salgam",
      "Boza",
      "Sahlep",
      "Soft Drink",
      "Water",
      "Other Beverage",
    ],
    "Fast Food": [
      "Hamburger",
      "Cheeseburger",
      "Chicken Burger",
      "French Fries",
      "Nuggets",
      "Hot Dog",
      "Tost",
      "Kasarli Tost",
      "Kumru",
      "Kokoreç",
      "Other Fast Food",
    ],
    "Pizza & Pasta": [
      "Margarita Pizza",
      "Mixed Pizza",
      "Pepperoni Pizza",
      "Sucuklu Pizza",
      "Spaghetti Bolognese",
      "Penne Arrabiata",
      "Fettuccine Alfredo",
      "Lasagna",
      "Makarna",
      "Other Pizza/Pasta",
    ],
    "Vegan & Vegetarian": [
      "Vegan Bowl",
      "Veggie Burger",
      "Stuffed Peppers",
      "Kuru Fasulye",
      "Zeytinyagli Yaprak Sarma",
      "Zeytinyagli Enginar",
      "Barbunya",
      "Nohut Yemegi",
      "Sebze Kizartma",
      "Other Vegan/Vegetarian",
    ],
    "World Cuisine": [
      "Chinese",
      "Japanese / Sushi",
      "Indian / Curry",
      "Mexican / Taco",
      "Thai",
      "Italian",
      "French",
      "Middle Eastern",
      "Korean",
      "American",
      "Other World Cuisine",
    ],
  };

  // ------------------------------------------------------
  // 3) Category Translation Keys
  // ------------------------------------------------------
  static readonly kCategoryTranslationKeys: Record<string, string> = {
    "Kebabs & Grills": "foodCategoryKebabsGrills",
    "Pide & Lahmacun": "foodCategoryPideLahmacun",
    Soups: "foodCategorySoups",
    Salads: "foodCategorySalads",
    "Appetizers & Meze": "foodCategoryAppetizers",
    "Main Courses": "foodCategoryMainCourses",
    "Rice & Pilaf": "foodCategoryRicePilaf",
    "Wraps & Doner": "foodCategoryWrapsDoner",
    Seafood: "foodCategorySeafood",
    Breakfast: "foodCategoryBreakfast",
    "Desserts & Pastry": "foodCategoryDesserts",
    Beverages: "foodCategoryBeverages",
    "Fast Food": "foodCategoryFastFood",
    "Pizza & Pasta": "foodCategoryPizzaPasta",
    "Vegan & Vegetarian": "foodCategoryVeganVegetarian",
    "World Cuisine": "foodCategoryWorldCuisine",
  };

  // ------------------------------------------------------
  // 4) Food Type Translation Keys
  // ------------------------------------------------------
  static readonly kFoodTypeTranslationKeys: Record<string, string> = {
    // Kebabs & Grills
    "Adana Kebab": "foodTypeAdanaKebab",
    "Urfa Kebab": "foodTypeUrfaKebab",
    "Iskender Kebab": "foodTypeIskenderKebab",
    "Shish Kebab": "foodTypeShishKebab",
    "Chicken Kebab": "foodTypeChickenKebab",
    Kofte: "foodTypeKofte",
    "Mixed Grill": "foodTypeMixedGrill",
    "Lamb Chops": "foodTypeLambChops",
    "Beyti Kebab": "foodTypeBeytiKebab",
    "Ali Nazik": "foodTypeAliNazik",
    "Cop Sis": "foodTypeCopSis",
    "Ciğer Kebab": "foodTypeCigerKebab",
    Tantuni: "foodTypeTantuni",
    "Other Kebab": "foodTypeOtherKebab",
    // Pide & Lahmacun
    "Cheese Pide": "foodTypeCheesePide",
    "Minced Meat Pide": "foodTypeMincedMeatPide",
    "Sucuklu Pide": "foodTypeSucukluPide",
    "Kasarli Pide": "foodTypeKasarliPide",
    "Kusbasi Pide": "foodTypeKusbasiPide",
    Lahmacun: "foodTypeLahmacun",
    "Etli Ekmek": "foodTypeEtliEkmek",
    "Other Pide": "foodTypeOtherPide",
    // Soups
    "Lentil Soup": "foodTypeLentilSoup",
    "Tomato Soup": "foodTypeTomatoSoup",
    "Chicken Soup": "foodTypeChickenSoup",
    "Tarhana Soup": "foodTypeTarhanaSoup",
    "Ezogelin Soup": "foodTypeEzogelinSoup",
    "Iskembe Soup": "foodTypeIskembeSoup",
    "Yayla Soup": "foodTypeYaylaSoup",
    "Mushroom Soup": "foodTypeMushroomSoup",
    "Mercimek Soup": "foodTypeMercimekSoup",
    "Other Soup": "foodTypeOtherSoup",
    // Salads
    "Shepherd Salad": "foodTypeShepherdSalad",
    "Caesar Salad": "foodTypeCaesarSalad",
    "Greek Salad": "foodTypeGreekSalad",
    "Seasonal Salad": "foodTypeSeasonalSalad",
    "Rocket Salad": "foodTypeRocketSalad",
    "Gavurdagi Salad": "foodTypeGavurdagiSalad",
    Piyaz: "foodTypePiyaz",
    "Coban Salad": "foodTypeCobanSalad",
    "Other Salad": "foodTypeOtherSalad",
    // Appetizers & Meze
    Hummus: "foodTypeHummus",
    Babaganoush: "foodTypeBabaganoush",
    Haydari: "foodTypeHaydari",
    Atom: "foodTypeAtom",
    "Acili Ezme": "foodTypeAciliEzme",
    Cacik: "foodTypeCacik",
    "Sigara Boregi": "foodTypeSigaraBoregi",
    "Icli Kofte": "foodTypeIcliKofte",
    "Mercimek Kofte": "foodTypeMercimekKofte",
    "Yaprak Sarma": "foodTypeYaprakSarma",
    Falafel: "foodTypeFalafel",
    Mucver: "foodTypeMucver",
    "Patlican Soslu": "foodTypePatlicanSoslu",
    "Other Meze": "foodTypeOtherMeze",
    // Main Courses
    Guvec: "foodTypeGuvec",
    Moussaka: "foodTypeMoussaka",
    "Imam Bayildi": "foodTypeImamBayildi",
    Karniyarik: "foodTypeKarniyarik",
    "Hunkar Begendi": "foodTypeHunkarBegendi",
    Manti: "foodTypeManti",
    "Su Boregi": "foodTypeSuBoregi",
    "Etli Nohut": "foodTypeEtliNohut",
    "Tas Kebab": "foodTypeTasKebab",
    "Sac Kavurma": "foodTypeSacKavurma",
    "Kuzu Tandir": "foodTypeKuzuTandir",
    Steak: "foodTypeSteak",
    "Chicken Schnitzel": "foodTypeChickenSchnitzel",
    "Other Main Course": "foodTypeOtherMainCourse",
    // Rice & Pilaf
    "Bulgur Pilaf": "foodTypeBulgurPilaf",
    "Rice Pilaf": "foodTypeRicePilaf",
    "Nohutlu Pilav": "foodTypeNohutluPilav",
    "Ic Pilav": "foodTypeIcPilav",
    "Domatesli Bulgur": "foodTypeDomatesliB",
    "Other Pilaf": "foodTypeOtherPilaf",
    // Wraps & Doner
    "Chicken Doner": "foodTypeChickenDoner",
    "Meat Doner": "foodTypeMeatDoner",
    "Iskender Doner": "foodTypeIskenderDoner",
    "Doner Wrap": "foodTypeDonerWrap",
    "Tavuk Durum": "foodTypeTavukDurum",
    "Et Durum": "foodTypeEtDurum",
    "Tombik Doner": "foodTypeTombikDoner",
    "Porsiyon Doner": "foodTypePorsiyonDoner",
    "Other Doner": "foodTypeOtherDoner",
    // Seafood
    "Grilled Fish": "foodTypeGrilledFish",
    "Fried Calamari": "foodTypeFriedCalamari",
    "Shrimp Casserole": "foodTypeShrimpCasserole",
    "Fish Sandwich": "foodTypeFishSandwich",
    Levrek: "foodTypeLevrek",
    Somon: "foodTypeSomon",
    Hamsi: "foodTypeHamsi",
    "Midye Tava": "foodTypeMidyeTava",
    "Midye Dolma": "foodTypeMidyeDolma",
    "Karides Guvec": "foodTypeKaridesGuvec",
    "Other Seafood": "foodTypeOtherSeafood",
    // Breakfast
    "Turkish Breakfast Plate": "foodTypeTurkishBreakfast",
    "Serpme Kahvalti": "foodTypeSerpmeKahvalti",
    Menemen: "foodTypeMenemen",
    "Sahanda Yumurta": "foodTypeSahandaYumurta",
    "Sucuklu Yumurta": "foodTypeSucukluYumurta",
    Gozleme: "foodTypeGozleme",
    Simit: "foodTypeSimit",
    Acma: "foodTypeAcma",
    Pogaca: "foodTypePogaca",
    "Other Breakfast": "foodTypeOtherBreakfast",
    // Desserts & Pastry
    Baklava: "foodTypeBaklava",
    Kunefe: "foodTypeKunefe",
    Sutlac: "foodTypeSutlac",
    Kazandibi: "foodTypeKazandibi",
    "Tavuk Gogsu": "foodTypeTavukGogsu",
    Asure: "foodTypeAsure",
    Revani: "foodTypeRevani",
    Lokma: "foodTypeLokma",
    Trilece: "foodTypeTrilece",
    Profiterol: "foodTypeProfiterol",
    Cheesecake: "foodTypeCheesecake",
    Tiramisu: "foodTypeTiramisu",
    Brownie: "foodTypeBrownie",
    Waffle: "foodTypeWaffle",
    Dondurma: "foodTypeDondurma",
    "Other Dessert": "foodTypeOtherDessert",
    // Beverages
    "Turkish Tea": "foodTypeTurkishTea",
    "Turkish Coffee": "foodTypeTurkishCoffee",
    Ayran: "foodTypeAyran",
    "Fresh Orange Juice": "foodTypeFreshOrangeJuice",
    Lemonade: "foodTypeLemonade",
    Smoothie: "foodTypeSmoothie",
    Salgam: "foodTypeSalgam",
    Boza: "foodTypeBoza",
    Sahlep: "foodTypeSahlep",
    "Soft Drink": "foodTypeSoftDrink",
    Water: "foodTypeWater",
    "Other Beverage": "foodTypeOtherBeverage",
    // Fast Food
    Hamburger: "foodTypeHamburger",
    Cheeseburger: "foodTypeCheeseburger",
    "Chicken Burger": "foodTypeChickenBurger",
    "French Fries": "foodTypeFrenchFries",
    Nuggets: "foodTypeNuggets",
    "Hot Dog": "foodTypeHotDog",
    Tost: "foodTypeTost",
    "Kasarli Tost": "foodTypeKasarliTost",
    Kumru: "foodTypeKumru",
    Kokoreç: "foodTypeKokorec",
    "Other Fast Food": "foodTypeOtherFastFood",
    // Pizza & Pasta
    "Margarita Pizza": "foodTypeMargaritaPizza",
    "Mixed Pizza": "foodTypeMixedPizza",
    "Pepperoni Pizza": "foodTypePepperoniPizza",
    "Sucuklu Pizza": "foodTypeSucukluPizza",
    "Spaghetti Bolognese": "foodTypeSpagBolognese",
    "Penne Arrabiata": "foodTypePenneArrabiata",
    "Fettuccine Alfredo": "foodTypeFettuccineAlfredo",
    Lasagna: "foodTypeLasagna",
    Makarna: "foodTypeMakarna",
    "Other Pizza/Pasta": "foodTypeOtherPizzaPasta",
    // Vegan & Vegetarian
    "Vegan Bowl": "foodTypeVeganBowl",
    "Veggie Burger": "foodTypeVeggieBurger",
    "Stuffed Peppers": "foodTypeStuffedPeppers",
    "Kuru Fasulye": "foodTypeKuruFasulye",
    "Zeytinyagli Yaprak Sarma": "foodTypeZeytinyagliSarma",
    "Zeytinyagli Enginar": "foodTypeZeytinyagliEnginar",
    Barbunya: "foodTypeBarbunya",
    "Nohut Yemegi": "foodTypeNohutYemegi",
    "Sebze Kizartma": "foodTypeSebzeKizartma",
    "Other Vegan/Vegetarian": "foodTypeOtherVeganVeg",
    // World Cuisine
    Chinese: "foodTypeChinese",
    "Japanese / Sushi": "foodTypeJapaneseSushi",
    "Indian / Curry": "foodTypeIndianCurry",
    "Mexican / Taco": "foodTypeMexicanTaco",
    Thai: "foodTypeThai",
    Italian: "foodTypeItalian",
    French: "foodTypeFrench",
    "Middle Eastern": "foodTypeMiddleEastern",
    Korean: "foodTypeKorean",
    American: "foodTypeAmerican",
    "Other World Cuisine": "foodTypeOtherWorldCuisine",
  };
}
